services:
  - type: web
    name: visionx-community-1
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://visionx-community-frontend.onrender.com

  - type: static
    name: visionx-community-frontend
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://visionx-community-1.onrender.com/api
